-- MySQL Script generated by MySQL Workbench
-- Mon Dec 20 23:12:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laundry
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `laundry` ;

-- -----------------------------------------------------
-- Schema laundry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laundry` DEFAULT CHARACTER SET utf8 ;
USE `laundry` ;

-- -----------------------------------------------------
-- Table `laundry`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laundry`.`users` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(20) NOT NULL,
  `pw` VARCHAR(20) NOT NULL,
  `apt_num` CHAR(3) NOT NULL,
  `time_slot` VARCHAR(45) NULL,
  `cpw` VARCHAR(20) NOT NULL,
  `booked_date` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
